// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7V4mC3hLAWrRvSS6Hkxd9sWzvDmcwV0',
    appId: '1:728365125634:web:b789599c8676b3120d971b',
    messagingSenderId: '728365125634',
    projectId: 'isi-cmi-prep',
    authDomain: 'isi-cmi-prep.firebaseapp.com',
    storageBucket: 'isi-cmi-prep.firebasestorage.app',
    measurementId: 'G-TGY46HLT4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK4ut4aT49AT2er1ppwEpoYqJhHpxzxA',
    appId: '1:728365125634:android:31d507c808c289720d971b',
    messagingSenderId: '728365125634',
    projectId: 'isi-cmi-prep',
    storageBucket: 'isi-cmi-prep.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7V4mC3hLAWrRvSS6Hkxd9sWzvDmcwV0',
    appId: '1:728365125634:web:0b918811c864362b0d971b',
    messagingSenderId: '728365125634',
    projectId: 'isi-cmi-prep',
    authDomain: 'isi-cmi-prep.firebaseapp.com',
    storageBucket: 'isi-cmi-prep.firebasestorage.app',
    measurementId: 'G-WRJK13BVP3',
  );
}
